//
//  BroadcastConfigManager.swift
//  MinecraftServerController
//
//  Manages MCXboxBroadcast config.yml lifecycle for a given server:
//  folder naming, YAML generation, surgical patching, and directory setup.
//
//  All methods are static and accept explicit parameters rather than
//  referencing app state, keeping this type parallel to GeyserConfigManager.
//

import Foundation

struct BroadcastConfigManager {

    // MARK: - Config template

    /// Base YAML template. Tokens __NAME__, __HOST__, __PORT__ are replaced at
    /// generation time via `makeConfigYaml(host:port:name:)`.
    static let configTemplate: String = """
    # Generated by MinecraftServerController for server "__NAME__"

    # Core session settings
    session:
      # How often (in seconds) to refresh the Xbox session info
      # Warning: This can be no lower than 20 due to Xbox rate limits
      update-interval: 30

      # Try to ping the Bedrock server to sync MOTD / online players automatically
      query-server: true

      # Use checker.geysermc.org to query if native ping fails
      web-query-fallback: false

      # Fall back to the config values below if all other server query methods fail
      config-fallback: false

      # The data to broadcast over Xbox Live when we can't query the server directly
      session-info:
        # What your friends see as the server name in the Friends tab
        host-name: "__NAME__"

        # Display name for the world/map (plain text is fine)
        world-name: "__NAME__ World"

        # Default player counts if we can't query them
        players: 0
        max-players: 20

        # Where the Bedrock client should connect
        ip: __HOST__
        port: __PORT__

    # Friend/follower list sync settings
    friend-sync:
      # How often (in seconds) to check for follower changes
      update-interval: 60

      # Automatically follow people that follow this Xbox account
      auto-follow: true

      # Automatically unfollow people that stop following this Xbox account
      auto-unfollow: true

      # Automatically send an invite when a friend is added
      initial-invite: true

      # Unfriend people that haven't joined the server in a while
      should-expire: true

      # How many days before a friend is considered "expired"
      expire-days: 15

      # How often (in seconds) to check for expired friends
      expire-check: 1800

    # Slack webhook settings (optional)
    slack-webhook:
      enabled: false
      webhook-url: ""

      session-expired-message: |
        Xbox Session expired, sign in again to update it.

        Use the following link to sign in: %s
        Enter the code: %s

      friend-restriction-message: |
        %s (%s) has restrictions in place that prevent them from being friends with this account.

    # Enable debug logs
    debug-log: false

    # Suppresses "Updated session!" log into debug
    suppress-session-update-info: false

    """

    // MARK: - Folder naming

    /// Returns a safe, human-readable directory name derived from the server's
    /// display name. Spaces and special characters are replaced with underscores.
    ///
    /// Examples:
    ///   "JC"             → "jc-broadcast"
    ///   "Project JC #1"  → "project_jc_1-broadcast"
    static func folderName(for server: ConfigServer) -> String {
        let raw = server.displayName
            .trimmingCharacters(in: .whitespacesAndNewlines)

        let baseSource = raw.isEmpty ? server.id : raw

        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_-"))
        let lower = baseSource.lowercased()
        let cleanedScalars = lower.unicodeScalars.map { scalar -> UnicodeScalar in
            allowed.contains(scalar) ? scalar : "_"
        }
        let cleaned = String(String.UnicodeScalarView(cleanedScalars))
        let trimmed = cleaned.trimmingCharacters(in: CharacterSet(charactersIn: "_-"))

        let finalBase = trimmed.isEmpty ? server.id : trimmed
        return "\(finalBase)-broadcast"
    }

    // MARK: - Config generation

    /// Fills the template with server-specific values to produce a ready-to-write
    /// config.yml. The caller is responsible for resolving `host` and `port`
    /// from app state before calling this method.
    static func makeConfigYaml(host: String, port: Int?, name: String) -> String {
        var yaml = configTemplate
        yaml = yaml.replacingOccurrences(of: "__HOST__", with: host)
        yaml = yaml.replacingOccurrences(of: "__NAME__", with: name)

        if let port {
            yaml = yaml.replacingOccurrences(of: "__PORT__", with: String(port))
        } else {
            yaml = yaml.replacingOccurrences(of: "        port: __PORT__\n", with: "")
            yaml = yaml.replacingOccurrences(of: "        port: __PORT__", with: "")
        }

        return yaml
    }

    // MARK: - Config patching

    /// Surgically patches the `ip:` and `port:` lines in an existing config.yml
    /// without rewriting the whole file, preserving user comments and structure.
    ///
    /// - If `port` is non-nil: updates an existing `port:` line, or inserts one
    ///   after `ip:` if the line is absent.
    /// - If `port` is nil: removes any existing `port:` line to avoid stale config.
    /// - Returns the original string unchanged if no modifications were needed.
    static func patchConfigYaml(_ text: String, host: String, port: Int?) -> String {
        var lines = text.components(separatedBy: .newlines)
        var didChange = false

        // Patch first "ip:" line.
        if let ipIndex = lines.firstIndex(where: { $0.trimmingCharacters(in: .whitespaces).hasPrefix("ip:") }) {
            let line = lines[ipIndex]
            let indent = line.prefix { $0 == " " || $0 == "\t" }
            let comment = line.range(of: "#").map { String(line[$0.lowerBound...]) } ?? ""
            let newLine = "\(indent)ip: \(host)\(comment.isEmpty ? "" : " \(comment)")"
            if lines[ipIndex] != newLine {
                lines[ipIndex] = newLine
                didChange = true
            }
        }

        let portIndex = lines.firstIndex(where: { $0.trimmingCharacters(in: .whitespaces).hasPrefix("port:") })

        if let port {
            if let portIndex {
                let line = lines[portIndex]
                let indent = line.prefix { $0 == " " || $0 == "\t" }
                let comment = line.range(of: "#").map { String(line[$0.lowerBound...]) } ?? ""
                let newLine = "\(indent)port: \(port)\(comment.isEmpty ? "" : " \(comment)")"
                if lines[portIndex] != newLine {
                    lines[portIndex] = newLine
                    didChange = true
                }
            } else if let ipIndex = lines.firstIndex(where: { $0.trimmingCharacters(in: .whitespaces).hasPrefix("ip:") }) {
                let ipLine = lines[ipIndex]
                let indent = ipLine.prefix { $0 == " " || $0 == "\t" }
                lines.insert("\(indent)port: \(port)", at: ipIndex + 1)
                didChange = true
            }
        } else {
            if let portIndex {
                lines.remove(at: portIndex)
                didChange = true
            }
        }

        var out = lines.joined(separator: "\n")
        if text.hasSuffix("\n") && !out.hasSuffix("\n") {
            out.append("\n")
        }

        return didChange ? out : text
    }

    // MARK: - Directory management

    /// Ensures the per-server Broadcaster config directory exists, handling
    /// migration from old ID-based folder names to the current human-friendly names.
    ///
    /// - Parameters:
    ///   - server: The server whose config directory is needed.
    ///   - rootURL: Root directory for all Broadcaster configs (caller-supplied).
    ///   - log: Closure used to emit status messages to the app console.
    ///   - persistPath: Called with the resolved directory path when a new path
    ///     is first determined. The caller should persist this to the server's
    ///     `xboxBroadcastConfigPath` field so future launches skip the resolution step.
    /// - Returns: The resolved directory URL, or `nil` on unrecoverable failure.
    @discardableResult
    static func ensureConfigDirectory(
        for server: ConfigServer,
        rootURL: URL,
        log: (String) -> Void,
        persistPath: ((String) -> Void)? = nil
    ) -> URL? {
        let fm = FileManager.default

        // 1) Ensure root exists.
        do {
            try fm.createDirectory(at: rootURL, withIntermediateDirectories: true)
        } catch {
            log("[Broadcast] Failed to create Broadcaster root directory: \(error.localizedDescription)")
            return nil
        }

        // 2) If a stored path already exists for this server, honor it.
        if let storedPath = server.xboxBroadcastConfigPath,
           !storedPath.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let storedURL = URL(fileURLWithPath: storedPath, isDirectory: true)
            var isDir: ObjCBool = false

            if !fm.fileExists(atPath: storedURL.path, isDirectory: &isDir) || !isDir.boolValue {
                do {
                    try fm.createDirectory(at: storedURL, withIntermediateDirectories: true)
                    log("[Broadcast] Recreated Broadcaster folder for \(server.displayName).")
                } catch {
                    log("[Broadcast] Failed to recreate Broadcaster folder for \(server.displayName): \(error.localizedDescription)")
                    return nil
                }
            }
            return storedURL
        }

        // 3) No stored path – resolve from old-style (ID) and new-style (name) locations.
        let oldDir = rootURL.appendingPathComponent(server.id, isDirectory: true)
        let newDir = rootURL.appendingPathComponent(folderName(for: server), isDirectory: true)

        var finalDir = newDir
        var isDir: ObjCBool = false

        let oldExists = fm.fileExists(atPath: oldDir.path, isDirectory: &isDir) && isDir.boolValue
        let newExists = fm.fileExists(atPath: newDir.path, isDirectory: &isDir) && isDir.boolValue

        if oldExists && !newExists {
            // Migrate: old ID-based folder → new human-friendly folder.
            do {
                try fm.moveItem(at: oldDir, to: newDir)
                finalDir = newDir
                log("[Broadcast] Migrated Broadcaster config for \(server.displayName) to new folder \(newDir.lastPathComponent).")
            } catch {
                finalDir = oldDir
                log("[Broadcast] Failed to migrate Broadcaster folder for \(server.displayName): \(error.localizedDescription)")
            }
        } else if newExists {
            finalDir = newDir
        } else if oldExists {
            finalDir = oldDir
        } else {
            // Neither exists – create from scratch.
            do {
                try fm.createDirectory(at: newDir, withIntermediateDirectories: true)
                finalDir = newDir
                log("[Broadcast] Created Broadcaster folder for \(server.displayName) at \(newDir.lastPathComponent).")
            } catch {
                log("[Broadcast] Failed to create Broadcaster folder for \(server.displayName): \(error.localizedDescription)")
                return nil
            }
        }

        // 4) Notify caller so the resolved path can be persisted.
        persistPath?(finalDir.path)

        return finalDir
    }

    // MARK: - Full sync

    /// Ensures the config directory exists and writes or patches `config.yml`
    /// to reflect the supplied host and port.
    ///
    /// - Creates `config.yml` from the template when it does not yet exist.
    /// - Patches only the `ip:` and `port:` lines when the file already exists,
    ///   preserving all other user edits and comments.
    /// - Returns the config directory URL so the caller can use it as a
    ///   working directory when launching the Broadcaster process.
    @discardableResult
    static func syncConfig(
        for server: ConfigServer,
        rootURL: URL,
        host: String,
        port: Int?,
        log: (String) -> Void,
        persistPath: ((String) -> Void)? = nil
    ) -> URL? {
        guard let dir = ensureConfigDirectory(
            for: server,
            rootURL: rootURL,
            log: log,
            persistPath: persistPath
        ) else { return nil }

        let cfgURL = dir.appendingPathComponent("config.yml")
        let fm = FileManager.default

        if !fm.fileExists(atPath: cfgURL.path) {
            let yaml = makeConfigYaml(host: host, port: port, name: server.displayName)
            do {
                try yaml.write(to: cfgURL, atomically: true, encoding: .utf8)
                log("[Broadcast] Created Broadcaster config.yml for \(server.displayName).")
            } catch {
                log("[Broadcast] Failed to create Broadcaster config.yml: \(error.localizedDescription)")
            }
            return dir
        }

        do {
            let original = try String(contentsOf: cfgURL, encoding: .utf8)
            let patched = patchConfigYaml(original, host: host, port: port)
            if patched != original {
                try patched.write(to: cfgURL, atomically: true, encoding: .utf8)
                log("[Broadcast] Synced Broadcaster config.yml for \(server.displayName).")
            }
        } catch {
            log("[Broadcast] Failed to sync Broadcaster config.yml: \(error.localizedDescription)")
        }

        return dir
    }
}
