// HeadlessScriptGenerator.swift
// MinecraftServerController

import Foundation

// MARK: - Options

enum HeadlessWrapMode: String, CaseIterable, Identifiable {
    case none        = "None"
    case autoRestart = "Auto-restart"
    case screen      = "screen"

    var id: String { rawValue }
}

enum HeadlessDockerRestart: String, CaseIterable, Identifiable {
    case never       = "Never"
    case onCrash     = "On crash"
    case always      = "Always"

    var id: String { rawValue }

    var dockerFlag: String {
        switch self {
        case .never:   return "no"
        case .onCrash: return "on-failure"
        case .always:  return "always"
        }
    }
}

// MARK: - Generator

enum HeadlessScriptGenerator {

    // MARK: - Java

    static func javaScript(
        config: ConfigServer,
        appConfig: AppConfig,
        minRamGB: Int,
        maxRamGB: Int,
        wrapMode: HeadlessWrapMode,
        includeXboxBroadcast: Bool
    ) -> String {
        let serverDir = config.serverDir
        let jarURL = URL(fileURLWithPath: (config.paperJarPath as NSString).expandingTildeInPath)
        let jarName = jarURL.lastPathComponent.isEmpty ? "paper.jar" : jarURL.lastPathComponent

        // Replicate exact flags from ServerProcessManager.startServer
        var jvmFlags: [String] = [
            "-Xms\(minRamGB)G",
            "-Xmx\(maxRamGB)G",
            "-Djna.nosys=true",
            "-Djna.nounpack=true",
            "-Djline.terminal=dumb",
            "-Dio.netty.noUnsafe=true",
        ]

        let extra = appConfig.extraFlags.trimmingCharacters(in: .whitespaces)
        if !extra.isEmpty {
            jvmFlags += extra.split { $0.isWhitespace }.map(String.init)
        }

        let javaCmd = buildJavaInvocation(javaPath: appConfig.javaPath, flags: jvmFlags, jar: jarName)

        var lines: [String] = [
            "#!/bin/bash",
            "# Generated by Minecraft Server Controller",
            "# Server: \(config.displayName)",
            "",
            "cd \(shellQuote(serverDir))",
            "",
        ]

        // Xbox Broadcast block
        if includeXboxBroadcast,
           let jarPath = appConfig.xboxBroadcastJarPath,
           !jarPath.isEmpty {
            lines += [
                "# Start MCXboxBroadcast (allows Xbox/Bedrock friends to join via LAN broadcast)",
                "java -jar \(shellQuote(jarPath)) &",
                "BROADCAST_PID=$!",
                "",
            ]
        }

        // Plugins info comment
        lines += [
            "# Plugins in your plugins/ folder will load automatically.",
            "",
        ]

        switch wrapMode {
        case .none:
            lines.append(javaCmd)

        case .autoRestart:
            lines += [
                "# Auto-restart: re-launches the server if it exits unexpectedly.",
                "while true; do",
                "    \(javaCmd)",
                "    echo \"[MSC] Server exited. Restarting in 5 seconds... (Ctrl+C to stop)\"",
                "    sleep 5",
                "done",
            ]

        case .screen:
            lines += [
                "# Runs in a detached screen session.",
                "# To reattach: screen -r minecraft",
                "# To detach:   Ctrl+A then D",
                "if ! command -v screen &>/dev/null; then",
                "    echo \"[MSC] Error: 'screen' is not installed. Install it with: brew install screen\"",
                "    exit 1",
                "fi",
                "screen -S minecraft \(javaCmd)",
            ]

        }

        // Broadcast cleanup (only for non-detached modes)
        if includeXboxBroadcast,
           let jarPath = appConfig.xboxBroadcastJarPath,
           !jarPath.isEmpty,
           wrapMode != .screen {
            lines += [
                "",
                "# Stop Xbox Broadcast helper when server exits",
                "kill $BROADCAST_PID 2>/dev/null",
            ]
        }

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Bedrock (Docker)

    static func bedrockScript(
        config: ConfigServer,
        dockerRestart: HeadlessDockerRestart
    ) -> String {
        let serverDir = config.serverDir
        let containerName = "psc-bds-\(String(config.id.replacingOccurrences(of: "-", with: "").prefix(12)))"
        let image = config.bedrockDockerImage ?? "itzg/minecraft-bedrock-server"

        let savedProps = BedrockPropertiesManager.readModel(serverDir: serverDir)
        let port = savedProps.serverPort
        let portV6 = savedProps.serverPortV6

        var runArgs: [(String, String?)] = [
            ("--name", containerName),
            ("-p", "\(port):\(port)/udp"),
            ("-v", "\(serverDir):/data"),
            ("-e", "EULA=TRUE"),
            ("-e", "SERVER_NAME=\(config.displayName)"),
            ("-e", "LEVEL_NAME=\(savedProps.levelName)"),
            ("-e", "MAX_PLAYERS=\(savedProps.maxPlayers)"),
            ("-e", "ONLINE_MODE=\(savedProps.onlineMode ? "true" : "false")"),
            ("-e", "ALLOW_CHEATS=\(savedProps.allowCheats ? "true" : "false")"),
            ("-e", "DIFFICULTY=\(savedProps.difficulty.bdsKey)"),
            ("-e", "GAMEMODE=\(savedProps.gamemode.bdsKey)"),
            ("-e", "SERVER_PORT=\(port)"),
            ("-e", "SERVER_PORT_V6=\(portV6)"),
            ("--restart=\(dockerRestart.dockerFlag)", nil),
        ]

        if config.maxRamGB > 0 {
            runArgs.append(("--memory", "\(config.maxRamGB)g"))
        }

        if let version = config.bedrockVersion,
           !version.isEmpty,
           version.uppercased() != "LATEST" {
            runArgs.append(("-e", "VERSION=\(version)"))
        }

        // Build readable multi-line docker run command
        var argLines: [String] = ["docker run -d \\"]
        for (flag, value) in runArgs {
            if let value {
                argLines.append("  \(flag) \(shellQuote(value)) \\")
            } else {
                argLines.append("  \(flag) \\")
            }
        }
        argLines.append("  \(image)")

        let lines: [String] = [
            "#!/bin/bash",
            "# Generated by Minecraft Server Controller",
            "# Server: \(config.displayName) (Bedrock / Docker)",
            "",
            "# Remove any existing stopped container with the same name",
            "docker rm -f \(containerName) 2>/dev/null || true",
            "",
            argLines.joined(separator: "\n"),
            "",
            "echo \"Container '\(containerName)' started on UDP port \(port).\"",
            "echo \"\"",
            "echo \"Useful commands:\"",
            "echo \"  View logs (live):  docker logs -f \(containerName)\"",
            "echo \"  Stop server:       docker stop \(containerName)\"",
            "echo \"  Remove container:  docker rm \(containerName)\"",
        ]

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Helpers

    private static func buildJavaInvocation(javaPath: String, flags: [String], jar: String) -> String {
        let trimmed = javaPath.trimmingCharacters(in: .whitespacesAndNewlines)
        let javaBin = trimmed.isEmpty ? "java" : trimmed
        let flagStr = flags.joined(separator: " ")
        return "\(javaBin) \(flagStr) -jar \(jar) --nogui"
    }

    private static func shellQuote(_ s: String) -> String {
        if s.rangeOfCharacter(from: .init(charactersIn: " \t\n\"'\\$`!#&;|<>(){}")) != nil {
            return "\"\(s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\""))\""
        }
        return s
    }
}
